# Based on pygit2's appveyor config
image: Visual Studio 2019
environment:
  matrix:
  - GENERATOR: 'Visual Studio 14'
    PYTHON: 'C:\Python38\python.exe'
  - GENERATOR: 'Visual Studio 14 Win64'
    PYTHON: 'C:\Python38-x64\python.exe'
  - GENERATOR: 'Visual Studio 14'
    PYTHON: 'C:\Python39\python.exe'
  - GENERATOR: 'Visual Studio 14 Win64'
    PYTHON: 'C:\Python39-x64\python.exe'

init:
  - cmd: '%PYTHON% -m pip install -U pip'
  - cmd: '%PYTHON% -m pip install -U nose'

build_script:
  # build and install `gl` binary (end to end test also use it)
  - cmd: '%PYTHON% -m pip install -r requirements.txt .'

before_test:
  - cmd: git config --global user.name "appveyor-test"
  - cmd: git config --global user.email "appveyor@test.com"

test_script:
  - cmd: dir /a:h
  - ps: |
      # 'gl' is installed in Python Scripts directory
      $env:PATH += ";$(Split-Path $env:PYTHON)\Scripts"
      &$env:PYTHON setup.py nosetests --logging-level=WARN --with-xunit
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))

branches:
  only:
    - master
