language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env: LIBGIT2=~/libgit2/_install/ LD_LIBRARY_PATH=~/libgit2/_install/lib

before_install: "./.travis.sh"

install: pip install .

before_script:
  - git config --global user.name "travis-test"
  - git config --global user.email "travis@test.com"

script:
  - nosetests --logging-level=WARN
  # nose doesn't like the number on test_e2e so it's not detected by the
  # previous command.
  - nosetests gitless/tests/test_e2e.py --logging-level=WARN

branches:
  only:
    - develop

sudo: false
